version: "3.9"

services:

  orderentry:
    image: dein-username/orderentry:latest
    container_name: orderentry
    ports:
      - "3000:3000"
    environment:
      - FHIR_BASE_URL=http://hapi.fhir.org/baseR4
      - AUTH_SECRET=dev-secret
      - NEXT_PUBLIC_SASIS_ENABLED=false
      - NEXT_PUBLIC_GLN_ENABLED=false
    volumes:
      - ./out/data:/app/data
      - ./out/logs:/app/logs
    restart: unless-stopped