import type { Metadata, Viewport } from "next";
import "./globals.css";
import pkg from "../../package.json";
import AppHeader from "@/components/AppHeader";
import Providers from "@/components/Providers";

export const dynamic = "force-dynamic";

const APP_VERSION = process.env.NEXT_PUBLIC_APP_VERSION || pkg.version || "0.0.0";
const SIMPLE_VERSION = (() => {
  const m = String(APP_VERSION).match(/(\d+\.\d+\.\d+)/);
  return m ? `v${m[1]}` : String(APP_VERSION);
})();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Force light mode across system-influenced UI
export const viewport: Viewport = {
  colorScheme: "light",
  themeColor: "#ffffff",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className="antialiased">
        <Providers>
          <AppHeader version={SIMPLE_VERSION} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
