import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="w-full border-b bg-gray-100 shadow-sm">
          <div className="mx-auto max-w-7xl px-6 py-4 text-center">
            <Image
              src="/logo.svg"
              alt="zetLab logo"
              width={48}
              height={48}
              className="mx-auto h-12 w-auto select-none"
            />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
